name: CI

on:
  push:
    branches:
      - main
      - next
    tags:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        target: [bundler, nodejs, web]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - if: ${{ matrix.target != 'nodejs' }}
        name: Optimize for size
        run: echo "opt-level = \"z\"" >> Cargo.toml

      - name: Build & zip
        run: |
          wasm-pack build --release --target ${{ matrix.target }} --out-dir pkg
          ls -ghG pkg
          tar -czvf rosu_pp_js_${{ matrix.target }}.tar.gz -C pkg .

      - name: Upload tarballs
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: rosu_pp_js_${{ matrix.target }}
          path: rosu_pp_js_${{ matrix.target }}.tar.gz

  release:
    name: Release
    needs: build
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: tars

      - name: Upload to github release
        uses: softprops/action-gh-release@v2
        with:
          files: tars/*.tar.gz

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Extract nodejs tarball
        run: |
          mkdir extracted
          tar -xzvf ./tars/rosu_pp_js_nodejs.tar.gz -C ./extracted

      - name: Change name of package
        run: |
          cd extracted
          sed -i 's/"name": "rosu-pp-js"/"name": "@osuAkatsuki\/rosu-pp-rs"/' package.json

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          package: ./extracted
          token: ${{ secrets.NPM_TOKEN }}
